(ns cedric.core-test
  (:require [cedric.core :as sut]
            [clojure.test :refer [deftest is testing]]))

(deftest ->rows-test
  (let [->rows #(sut/->rows % {:id 0 :attribute "value"})]
    (testing "Returns a collection of rows with entity, attribute and value."
      (is (= [[[:id 0] :attribute "value" nil]]
             (->rows {:entity-attribute :id})))
      (is (= [[[:attribute "value"] :id 0 nil]]
             (->rows {:entity-attribute :attribute}))))
    (testing "returns nil when entity can't be found" 
      (is (nil? (->rows {:entity-attribute :unknown}))))))

(deftest entity->map-test
  (is (= {:id 0} (sut/entity->map [:id 0])))
  (is (= {:a :b :id 0} (sut/entity->map {:a :b} [:id 0]))))

(deftest ->map-test
  (is (= {::sut/destroyed-entity [:id 0]}
         (-> (sut/->map {::sut/entity [:id 0] ::sut/attribute :a ::sut/value "v" ::sut/delete-or-destroy :destroy!}) meta))))

(deftest merge-items-test
  (is (= {[:id 0] {:attribute1 "value1"}}
         (#'sut/merge-items {[:id 0] {:attribute1 "value1"}}
                            (with-meta
                              {[:id 1] {:attribute2 "value2"}}
                              {::sut/destroyed-entity [:id 1]}))))
  (is (= {[:id 0] {:id 0 :attribute1 "value1"}}
         (#'sut/merge-items {[:id 0] {:id 0}} {[:id 0] {:attribute1 "value1"}})))
  (is (= nil (#'sut/merge-items nil nil))))

(deftest combine-test
  (let [rows [[[:id 0] :attribute1 "value1" false]
              [[:id 0] :attribute2 "value2" false]
              [[:id 1] :attribute3 "value3" false]
              [[:user 3] :attribute4 "value4" false]]]
    (testing "combine returns a db map with all items"
      (is (= {[:id 0]   {:id 0 :attribute1 "value1" :attribute2 "value2"}
              [:id 1]   {:id 1 :attribute3 "value3"}
              [:user 3] {:user 3 :attribute4 "value4"}}
             (sut/combine rows))))
    (testing "returns a db-map with only items filtered by entity"
      (is (= {[:user 3] {:user 3 :attribute4 "value4"}}
             (sut/combine {:entity-pred (comp #{:user} first)} rows)))
      (is (= {[:id 1] {:id 1 :attribute3 "value3"}}
             (sut/combine {:entity-pred (comp #{1} second)} rows))))
    (testing "doesn't return the destroyed items"
      (is (= {[:id 1]   {:id 1 :attribute3 "value3"}
              [:user 3] {:user 3 :attribute4 "value4"}}
             (sut/combine (conj rows [[:id 0] :attribute1 "value1" :destroy!])))))
    (testing "doesn't return deleted attributes"
      (is (= {[:id 0]   {:id 0 :attribute2 "value2"}
              [:id 1]   {:id 1 :attribute3 "value3"}
              [:user 3] {:user 3 :attribute4 "value4"}}
             (sut/combine (conj rows [[:id 0] :attribute1 "value1" :delete!])))))))

(deftest generate-entity-test
(let [props     {:entity-attribute :id}
      db        #{[:id 0] [:id 1]}
      generator #(lazy-seq (repeat 99))]
  (testing "returns the next available entity"
    (is (= [:id 2] (sut/generate-entity props db))))
  (testing "returns the next available entity generated by the ev generator"
    (is (= [:id 99] (sut/generate-entity
                      (assoc props :entity-value-generator generator)
                      db))))))
