(ns cedric.core-test
  (:require [cedric.core :as sut]
            [clojure.test :refer [deftest is testing]]))

(deftest ->rows-test
  (let [->rows #(sut/->rows % {:id 0 :attribute "value"})]
    (testing "Returns a collection of rows with entity, attribute and value."
      (is (= [[[:id 0] :attribute "value"]]
             (->rows {:entity-attribute :id})))
      (is (= [[[:attribute "value"] :id 0]]
             (->rows {:entity-attribute :attribute}))))
    (testing "returns nil when entity can't be found" 
      (is (nil? (->rows {:entity-attribute :unknown}))))))

(deftest combine-test
  (let [rows [[[:id 0] :attribute1 "value1"]
              [[:id 0] :attribute2 "value2"]
              [[:id 1] :attribute3 "value3"]]]
    (is (= {[:id 0] {:id 0 :attribute1 "value1" :attribute2 "value2"}
            [:id 1] {:id 1 :attribute3 "value3"}}
           (sut/combine rows)))))

(deftest generate-entity-test
  (let [props     {:entity-attribute :id}
        db        #{[:id 0] [:id 1]}
        generator #(lazy-seq (repeat 99))]
    (testing "returns the next available entity"
      (is (= [:id 2] (sut/generate-entity props db))))
    (testing "returns the next available entity generated by the ev generator"
      (is (= [:id 99] (sut/generate-entity
                        (assoc props :entity-value-generator generator)
                        db))))))
