name: clj workflow

on: [push]

jobs:
  clojure:
    strategy:
      matrix:
        os: [ubuntu-latest macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'
      
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          cli: 1.10.1.693
      
      - name: Run clj tests
        run: clojure -X:test
        
  #clojurescript:
